### ISSUE TITLE
Notice: Undefined offset: 0

### ISSUE THREAD

**Issue by nkl90** [Nekland/YoutubeApi#11]
[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined offset: 0                                
                                                             

Exception trace:
 () at /home/nkl/projects/youtube-crawler/vendor/nekland/youtube-api/lib/Nekland/YoutubeApi/Api/Behavior/ListTrait.php:42
 Nekland\YoutubeApi\Api\Videos->getById() at /home/nkl/projects/youtube-crawler/src/AppBundle/Command/ChannelCrawlerCommand.php:60
 AppBundle\Command\ChannelCrawlerCommand->execute() at /home/nkl/projects/youtube-crawler/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/nkl/projects/youtube-crawler/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:887
 Symfony\Component\Console\Application->doRunCommand() at /home/nkl/projects/youtube-crawler/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /home/nkl/projects/youtube-crawler/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/nkl/projects/youtube-crawler/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /home/nkl/projects/youtube-crawler/bin/console:27

crawler:start [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by Nek-** [comment]
Hello, can you provide more explanation about how you got this error ?

**Comment by nkl90** [comment]
If on line 28 in file vendor/nekland/base-api/lib/Nekland/BaseApi/Api/AbstractApi.php json_decode() return empty array.

**Comment by Nek-** [comment]
@nkl90 After some tests, the issue is not from YoutubeApi but because the video you're asking for doesn't exists. We decided to fix this by adding a new kind of error and release a new version of YoutubeApi. Feel free to [check what changed](https://github.com/Nekland/YoutubeApi/issues/12) and contribute if you want more.

пока
